CREATE TABLE IF NOT EXISTS GAMES
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME          TEXT NOT NULL,
    GENRE         TEXT,
    RELEASE_DATE  DATE,
    COUCH_PLAYERS INTEGER,
    SPLIT_SCREEN  INTEGER
);