CREATE TABLE IF NOT EXISTS GAMES
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME          TEXT NOT NULL,
    GENRE         TEXT,
    RELEASE_DATE  DATE,
    COUCH_PLAYERS INTEGER,
    SPLIT_SCREEN  INTEGER,
    MC_USERS_SCORE NUMERIC,
    MC_CRITICS_SCORE NUMERIC

);